language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
      addons:
        apt:
          packages:
            - p7zip

    - env: TARGET=msp430-none-elf
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
      addons:
        apt:
          packages:
            - p7zip

before_install: set -e

install:
  - bash ci/install.sh
  - export PATH="$PATH:$PWD/msp430-gcc-8.3.1.25_linux64/bin"

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
